import os
import sys
import time
import base64
import requests

bs64 = base64.b64decode("UHJveHkgc2NyYXBlciBjb2RlZCBieSBGNEFHMA==").decode("UTF-8")

print('Proxy scraper coded by F4AG0 starting')
time.sleep(2)
os.system('cls')
sys.stdout.write('\rloading |')
time.sleep(0.1)
sys.stdout.write('\rloading /')
time.sleep(0.1)
sys.stdout.write('\rloading -')
time.sleep(0.1)
sys.stdout.write('\rloading \\')
time.sleep(0.1)
sys.stdout.write('\rloading |')
time.sleep(0.1)
sys.stdout.write('\rloading /')
time.sleep(0.1)
sys.stdout.write('\rloading -')
time.sleep(0.1)
sys.stdout.write('\rloading \\')
time.sleep(0.1)
sys.stdout.write('\rloading |')
time.sleep(0.1)
sys.stdout.write('\rloading /')
time.sleep(0.1)
sys.stdout.write('\rloading -')
time.sleep(0.1)
sys.stdout.write('\rloading \\')
time.sleep(0.1)
sys.stdout.write('\rloading |')
time.sleep(0.1)
sys.stdout.write('\rloading /')
time.sleep(0.1)
sys.stdout.write('\rloading -')
time.sleep(0.1)
sys.stdout.write('\rloading \\')
sys.stdout.write('\rDone started!     ')
os.system("cls")

print(f"""
||
| {bs64}
||
| Proxy types http, https, socks4, socks5
|
""")
typeproxy = input('choose a proxy type: ')
proxy = f'{typeproxy}'

f = open('proxy.txt','wb')
api1 = requests.get(f"https://api.proxyscrape.com/v2/?request=getproxies&protocol={proxy}&timeout=10000&country=all")
os.system('cls')
print('Proxy scraping...')
time.sleep(2)
os.system('cls')
sys.stdout.write('\rScraping |')
time.sleep(0.1)
sys.stdout.write('\rScraping /')
time.sleep(0.1)
sys.stdout.write('\rScraping -')
time.sleep(0.1)
sys.stdout.write('\rScraping \\')
time.sleep(0.1)
sys.stdout.write('\rScraping |')
time.sleep(0.1)
sys.stdout.write('\rScraping /')
time.sleep(0.1)
sys.stdout.write('\rScraping -')
time.sleep(0.1)
sys.stdout.write('\rScraping \\')
time.sleep(0.1)
sys.stdout.write('\rScraping |')
time.sleep(0.1)
sys.stdout.write('\rScraping /')
time.sleep(0.1)
sys.stdout.write('\rScraping -')
time.sleep(0.1)
sys.stdout.write('\rScraping \\')
time.sleep(0.1)
sys.stdout.write('\rScraping |')
time.sleep(0.1)
sys.stdout.write('\rScraping /')
time.sleep(0.1)
sys.stdout.write('\rScraping -')
time.sleep(0.1)
sys.stdout.write('\rScraping \\')
sys.stdout.write('\rDone all proxies scraped!     ')
time.sleep(2)
os.system("cls")
f.write(api1.content)
f.close()